### ISSUE TITLE
Wrong result for prerelease comparison

### ISSUE THREAD

**Issue by hoesler** [Masterminds/vert#8]
I have a problem comparing a stable version with a prerelease. I am expecting 2.0.0-rc.1 to be greater than 1.0.0, but vert says it's not:

```sh
vert ">1.0.0" "2.0.0-rc.1"
echo $? # returns 1
```

**Comment by Nuru** [comment]
No, that is correct. A pre-release (anything with a dash after the third number) never substitutes for a production release. See section on Prerelease Tags at https://www.npmjs.com/package/semver
